In [1]:
import numpy as np

In [2]:
# Scalars
x = 2
print x

2


# Tensors

A **vector** is a collection of scalars.  
For instance, two coordinates $(x, y)$ to represent a point on a plane.

In general, we say that a vector is $n$-dimensional, i.e. in $\mathbb{R}^n$.  
In particular, the following example is in $\mathbb{R}^3$.

In [3]:
# Vectors
x = np.array( [1, 2, 1] )
print x
print x.shape

[1 2 1]
(3,)


A **matrix** instead is said to be in $R^{m \times n}$.  
In particular, the following example belongs to $R^{2 \times 3}$

In [4]:
# Matrices
x = np.array([[1, 2, 1],
              [2, 1, 2]])
print x
print x.shape

[[1 2 1]
 [2 1 2]]
(2, 3)


**Tensors** generalize the concept of matrices to higher orders.  
An $N^{th}$ order tensor belongs to the set $R^{n_1 \times n_2 \times \dots \times n_N}$.  
In particular, the following example is in $R^{4 \times 2 \times 3}$:

In [5]:
x = np.array([[[1, 2, 1], [2, 1, 2]],
              [[1, 2, 1], [2, 1, 2]],
              [[1, 2, 1], [2, 1, 2]],
              [[1, 2, 1], [2, 1, 2]]])
print x
print x.shape

[[[1 2 1]
  [2 1 2]]

 [[1 2 1]
  [2 1 2]]

 [[1 2 1]
  [2 1 2]]

 [[1 2 1]
  [2 1 2]]]
(4, 2, 3)


Note that matices of size $m \times n$ can be flattened out to form a vector of size $mn$.  
Similarly, tensors can be flattened out to form vectors of size $n_1 n_2 \dots n_N$.  

We say that the two spaces are **isomorphic**.

# Vector Space

$\mathbb{R}^3$ over $\mathbb{R}$ gives us the coordinate system for 3 dimensional geometry.  
A **vector space** $V$ over $F$ is a generalization of this notion.

First, we have an operator $+$:
1. $x, y \in V \implies x + y \in V$
2. $x + y = y + x$, i.e. $+$ is **commutative**
3. $x + (y + z) = (x + y) + z$, i.e. $+$ is **associative**
4. There is a **zero** such that $x + 0 = 0 + x = x$
4. There is an **additive inverse** such that $x + (-x) = (-x) + x = 0$

We also have an operator $\cdot$, for scalar multiplication:
1. $x \in V, \alpha \in R \implies \alpha \cdot x \in V$
2. $\alpha \cdot (x + y) = \alpha \cdot x + \alpha \cdot y$
3. $(\alpha + \beta) \cdot x = \alpha \cdot x + \beta \cdot x$
4. $(\alpha \beta) \cdot x = \alpha \cdot (\beta \cdot x)$
5. There is a **one** such taht $1 \cdot x = x$

# Distance

Let's take a moment to go back to vectors.

In [6]:
x1 = np.array([1, -2, 1])
x2 = np.array([0, 1, 3])

We can measure the standard Euclidean distance between these vectors:  
$$\lVert x_1 - x_2\rVert_2 = \sqrt{\sum_{i=0}^2 ((x_1)_i - (x_2)_i)^2}$$

In [7]:
distance = 0

for i in range(3):
    distance += (x1[i] - x2[i]) ** 2

distance = distance ** 0.5
print distance

3.74165738677


The quantity $\lVert x \lVert_2$ is called the **Euclidean norm** or **$L_2$ norm**.  
Here's a handy helper method that allows us to compute the distance:

In [8]:
print np.linalg.norm(x1 - x2)
print x1-x2

3.74165738677
[ 1 -3 -2]


There are a number of other useful norms:
1. **$L_2$ norm:** $$\lVert x \rVert_1 = \sum_{i} \left| x_i \right|$$
2. **$L_1$ norm:** $$\lVert x \rVert_2 = \sqrt{\sum_{i} x_i^2}$$
3. **Infinity norm:** $$\lVert x \rVert_\infty = \arg\max_{i} \left| x_i \right|$$

In [9]:
print x1 - x2
print np.linalg.norm(x1 - x2, ord=1)
print np.linalg.norm(x1 - x2, ord=2)
print np.linalg.norm(x1 - x2, ord=np.inf)

[ 1 -3 -2]
6.0
3.74165738677
3.0


# Inner Product Space and Distance Metrics

$(\mathbb{R}^3, \lVert \cdot \rVert_2)$ forms the basis for Euclidean 3 dimensional geometry.  
We can generalize this to the notion of a **inner product space** of $(V, d)$.

In particular, we say that $d$ is a distance if it satisfies:  
1. Non-negativity: $d(x,y) \ge 0$ and $d(x, y) = 0 \iff x = y$
2. Symmetric: $d(x,y) = d(y,x)$
3. Triangle inequality: $d(x,z) \le d(x,y) + d(y,z)$

**Try it!**  
Check that $\lVert \cdot \rVert_1$ and $\lVert \cdot \rVert_\infty$ are valid distance metrics.

# Linear Independence and Basis

A set of vectors $x_1, x_2, \dots x_n$ is said to be **linearly independent** if there is no way to write one as a linear combination of the others, i.e.:

$$x_i \neq \sum_{j \ne i} \alpha_j x_j$$

Consider:

In [10]:
x1 = np.array([1, 0, 0])
x2 = np.array([0, 1, 0])
x3 = np.array([0, 0, 1])

print x1, "\n", x2, "\n", x3

[1 0 0] 
[0 1 0] 
[0 0 1]


It's easy to see that you cannot express $(1, 0, 0)$ as a sum of $(0, 1, 0)$ and $(0, 0, 1)$.

A **basis** is a set of linearly independent vectors that make up the whole space.  
It is easy to see that $x_1$, $x_2$, $x_3$ as defined above make up the whole of $\mathbb{R}^3$:

In [11]:
x = np.random.randint(1, 1000, size=(3,))
print x
print x[0] * x1 + x[1] * x2 + x[2] * x3

[444 178 250]
[444 178 250]


**Result:** Any linearly independent set of cardinality $N$ is a basis of $\mathbb{R}^N$ (why?).