In [1]:
import numpy as np

# Diagonalization

We say that a matrix $A$ is diagonalizable if there exists a matrix $P$ such that:

$$P^{-1} A P = D = diag(\lambda_1, \lambda_2, \dots, \lambda_n)$$

In [2]:
A = np.array([[1, 1],
              [0, 2]])
P = np.array([[1, 1],
              [0, 1]])

print "A:\n", A, "\n"
print "P:\n", P

A:
[[1 1]
 [0 2]] 

P:
[[1 1]
 [0 1]]


In [3]:
print np.matmul(np.matmul(np.linalg.inv(P), A), P)

[[ 1.  0.]
 [ 0.  2.]]


Here, $\lambda_1 = 1$ and $\lambda_2 = 2$.  
So, clearly, A is diagonalizable.

**Note:** Not all real matrices are diagonalizable over $\mathbb{R}$. For example (try this at home):

In [4]:
print np.array([[0, -1],
                [1, 0]])

[[ 0 -1]
 [ 1  0]]


All real matrices are diagonalizable over $\mathbb{C}$. (i.e. $\lambda_i \in \mathbb{C}$).

# Eigenvalues and Eigenvectors

$\lambda$ is an **eigenvalue** of a matrix $A$ if there exists a non-zero vector v $v$ such that:

$$A \phi = \lambda \cdot \phi$$

The vector $\phi$ is called an **eigenvector**. These are vectors that are invariant *in direction* under $A$.  
Together, $(\lambda, \phi)$ constitute an **eigenpair**.

In [5]:
A = np.array([[1, 1],
              [0, 2]])
v = np.array([1, 0])

print "A:\n", A, "\n"
print "v:\n", v

A:
[[1 1]
 [0 2]] 

v:
[1 0]


In [6]:
print np.matmul(A, v)
print 1 * v

[1 0]
[1 0]


Clearly, $\lambda = 1$ is an eigenvalue!

In [7]:
A = np.array([[1, 1],
              [0, 2]])
v = np.array([1, 1])

print "A:\n", A, "\n"
print "v:\n", v

A:
[[1 1]
 [0 2]] 

v:
[1 1]


In [8]:
print np.matmul(A, v)
print 2 * v

[2 2]
[2 2]


Clearly, $\lambda = 2$ is an eigenvalue!

This is no accident! Recall the value of P:

In [9]:
print "P:\n", P

P:
[[1 1]
 [0 1]]


The $v$'s that we selected correspond to the **columns** of $P$!  

# Eigendecomposition

Rewriting $A = P D P^{-1}$, we have the following:

$$A = P^{-1} \Lambda P$$

where $\Lambda$ is a diagonal matrix of eigenvalues $= diag(\lambda_1, \lambda_2, \dots \lambda_N)$ and the columns of $P$ constitute the eigenvalues of $A$.

We can retreive the eigenpairs with the library function `np.linalg.eig`:

In [10]:
eigval, eigvec = np.linalg.eig(A)

print "The matrix A:\n", A, "\n"

for i in range(2):
    print 'λ_%d:' % (i+1), eigval[i]
    print 'v_%d:' % (i+1), eigvec[:,i]

The matrix A:
[[1 1]
 [0 2]] 

λ_1: 1.0
v_1: [ 1.  0.]
λ_2: 2.0
v_2: [ 0.70710678  0.70710678]


**Be careful!** The eigendecomposition might yield complex eigenvalues!  
**Note:** Symmetric matrices only have real eigenvalues.

"Proof" by sampling

In [11]:
for _ in range(5):
    A = np.random.randint(0, 100, size=(3,3))
    
    for i in range(3):
        for j in range(i):
            A[j,i] = A[i,j]

    eigval, _ = np.linalg.eig(A)
    print eigval

[ -53.99058899  154.45343582   52.53715317]
[ 193.01737063   11.70761952   33.27500985]
[ 221.68587334  -33.29034621   18.60447287]
[ 162.01388532    0.17212057  -63.18600588]
[ 173.58551294   -2.93459405  -73.6509189 ]


Assymetric matrices: counterexample

In [12]:
while True:
    A = np.random.randint(0, 100, size=(3,3))
    eigval, _ = np.linalg.eig(A)
    
    quit = False
    
    for v in eigval:
        if np.imag(v) != 0:
            quit = True
           
    if quit:
        break

print A, "\n"

for i, v in enumerate(eigval):
    print 'v_%d:' % (i+1), v

[[74 55 69]
 [65 80 45]
 [11 78 54]] 

v_1: (177.852603322+0j)
v_2: (15.0736983392+28.3370894016j)
v_3: (15.0736983392-28.3370894016j)


# Singular Value Decomposition

Yet another useful matrix decomposition is SVD. Consider a non-square matrix, $A \in \mathbb{R}^{m \times n}$. Then:

$$A = U \Sigma V^T$$

where:

1. $\Sigma$ is the diagonal matrix of **singular values**, the square roots of eigenvalues of the matrix $A^T A$.
2. The columns of $U$ form a basis for $R^{n}$
2. The columns of $V$ form a basis for $R^{m}$

Furthermore, each eigenvector is normalized such that:

1. $\lVert v \rVert_2 = 1$ for all $v$, i.e. they are all **unit vectors**
1. $v_1^T v_2 = 0$, i.e. they are **perpendicular to each other**

In [13]:
A = np.array([[1, 1],
              [0, 2]])

u, s, v = np.linalg.svd(A)
eigval, _ = np.linalg.eig(np.matmul(A.T, A))

print "The matrix A:\n", A, "\n"
print "The matrix A^T A:\n", np.matmul(A.T, A), "\n"

for i in range(2):
    print 's_%d:' % (i+1), s[i] ** 2

print ''
    
for i in range(2):
    print 'λ_%d:' % (i+1), eigval[i]

The matrix A:
[[1 1]
 [0 2]] 

The matrix A^T A:
[[1 1]
 [1 5]] 

s_1: 5.2360679775
s_2: 0.7639320225

λ_1: 0.7639320225
λ_2: 5.2360679775


In [14]:
print 'u1:', u[:,0]
print 'u2:', u[:,1]

u1: [ 0.52573111  0.85065081]
u2: [-0.85065081  0.52573111]


In [15]:
print 'v1:', u[:,0]
print 'v2:', u[:,1]

v1: [ 0.52573111  0.85065081]
v2: [-0.85065081  0.52573111]
